language: node_js
node_js:
 - "stable"
cache:
 directories:
   - node_modules
script:
 - npm run test
after_success:
- npm run coveralls
notifications:
 email: false
services:
- postgresql
before_script:
- psql -c "create database testsdb;" -U postgres